export const FETCH_COOPS_START = 'FETCH_COOPS_START'
export const FETCH_COOPS_SUCCESS = 'FETCH_COOPS_SUCCESS'
export const FETCH_COOPS_FAIL = 'FETCH_COOPS_FAIL'

export const FETCH_PLATFORMS_START = 'FETCH_PLATFORMS_START'
export const FETCH_PLATFORMS_SUCCESS = 'FETCH_PLATFORMS_SUCCESS'
export const FETCH_PLATFORMS_FAIL = 'FETCH_PLATFORMS_FAIL'
