export const FETCH_REQESTS_START = 'FETCH_REQESTS_START'
export const FETCH_REQESTS_SUCCESS = 'FETCH_REQESTS_SUCCESS'
export const FETCH_REQESTS_FAIL = 'FETCH_REQESTS_FAIL'

export const FETCH_PLATFORMS_START = 'FETCH_PLATFORMS_START'
export const FETCH_PLATFORMS_SUCCESS = 'FETCH_PLATFORMS_SUCCESS'
export const FETCH_PLATFORMS_FAIL = 'FETCH_PLATFORMS_FAIL'
